# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 550)
        Form.setWindowOpacity(1.0)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(500, 80, 85, 27))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 471, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(20, 60, 311, 17))
        self.label1.setObjectName("label1")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(220, 20, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.status_label = QtWidgets.QLabel(Form)
        self.status_label.setGeometry(QtCore.QRect(20, 200, 54, 17))
        self.status_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.status_label.setObjectName("status_label")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 230, 561, 281))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.cb_mtbf = QtWidgets.QCheckBox(Form)
        self.cb_mtbf.setGeometry(QtCore.QRect(400, 120, 101, 22))
        self.cb_mtbf.setObjectName("cb_mtbf")
        self.cb_fit = QtWidgets.QCheckBox(Form)
        self.cb_fit.setGeometry(QtCore.QRect(270, 152, 101, 22))
        self.cb_fit.setObjectName("cb_fit")
        self.cb_extra = QtWidgets.QCheckBox(Form)
        self.cb_extra.setGeometry(QtCore.QRect(400, 150, 86, 22))
        self.cb_extra.setObjectName("cb_extra")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(120, 120, 111, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 180, 221, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 130, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 130, 131, 17))
        self.label_2.setObjectName("label_2")
        self.mtbf_label = QtWidgets.QLabel(Form)
        self.mtbf_label.setGeometry(QtCore.QRect(20, 520, 561, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mtbf_label.setFont(font)
        self.mtbf_label.setText("")
        self.mtbf_label.setObjectName("mtbf_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MTBF search"))
        self.pushButton.setText(_translate("Form", "Find"))
        self.label1.setText(_translate("Form", "Component name:"))
        self.title.setText(_translate("Form", "MTBF search"))
        self.status_label.setText(_translate("Form", "Status..."))
        self.cb_mtbf.setText(_translate("Form", "MTBF, MTTF"))
        self.cb_fit.setText(_translate("Form", "FIT (failures)"))
        self.cb_extra.setText(_translate("Form", "Extra tags"))
        self.comboBox.setItemText(0, _translate("Form", "Google"))
        self.comboBox.setItemText(1, _translate("Form", "Yandex"))
        self.label.setText(_translate("Form", "Search engine:"))
        self.label_2.setText(_translate("Form", "Tags for searching:"))

